# Generated by Django 4.2.1 on 2023-07-17 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='galleries', to=settings.AUTH_USER_MODEL),
        ),
    ]
