# Generated by Django 4.2.1 on 2023-07-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_gallery_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizedphoto',
            name='image_subtype',
            field=models.CharField(max_length=20),
        ),
    ]
