# Generated by Django 4.2.1 on 2023-08-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_alter_optimizedphoto_image_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='displayed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
