# Generated by Django 4.2.1 on 2023-09-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_galleryarchive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='type',
            new_name='gallery_type',
        ),
    ]
