# Generated by Django 4.2.1 on 2023-07-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
