# Generated by Django 4.2.1 on 2023-07-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_day_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
