# Generated by Django 4.2.1 on 2023-07-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_day_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='first_name',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='last_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='message',
            field=models.CharField(blank=True, max_length=1800, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
