# Generated by Django 4.2.1 on 2023-08-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_day_first_name_day_last_name_day_message_day_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='first_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
